### ISSUE TITLE
Make the example project offline

### ISSUE THREAD

**Issue by ppxl** [cloudogu/spring-petclinic#6]
For certain circumstances (like customers with hosting on-premise) internet access is not available. For now the only part that blocks a pure offline usage is the incorporation of the `ces-build-lib` which needs internet access.

Please support offline availability.

**Comment by schnatterer** [comment]
I'd like to elaborate on this a bit.

What does not work for an offline Jenkins is loading a Jenkins shared library via the "Pipeline: GitHub Groovy Libraries plugin".
The other option is to load a shared library as "Global Pipeline Libraries". 
For the `ces-build-lib` it would be possible to push it to a local Git repo and configure it as "Global Pipeline Libraries" using the name `github.com/cloudogu/ces-build-lib`.
When running the `spring-petclinic` Jenkinsfile in a setup like this, the following error occurred:
`No such field: script for class: com.cloudogu.ces.cesbuildlib.MavenWrapper"`.

This issues is documented as [JENKINS-44183](https://issues.jenkins-ci.org/browse/JENKINS-44183) and the the workaround mentioned there is implemented in cloudogu/ces-build-lib@c62227398d694c7b4951b881eb49fe8e4b33aae6.
